"""Analyze verified public C++ sources through runtime roles, then score offline.

No oracle fields enter discovery, snapshots, source tools or role prompts. The
lexical discovery plugin and observation-only evaluator are intentionally small;
semantic confirmation requires a separate rule/backend implementation.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import json
import platform
import time
import uuid
from pathlib import Path
from urllib.parse import urlsplit

from agent_runtime import (
    CandidateIdentity, CheckDefinition, CheckItem, DefectRuntime,
    FactAssessment, FixedSnapshot, InvalidInput, Profile, QueryRequest,
    RoleCoordinator, RoleDefinition, RuleSpec, SQLiteStore,
    analysis_profile_digest, bytes_digest, canonical_json, digest,
    CppUnreachableEvaluator, EvidenceReviewExecutor,
)
from agent_runtime.adapters import (
    ClaudeAgentExecutor, ClaudeConfig, FrozenSourceProgramQuery,
    RecordedJoernProgramQuery,
)
from agent_runtime.codec import to_plain, utc_now
from agent_runtime.evaluation import (
    dataset_manifest_digest, fetch_verified_artifact, load_json_object,
    validate_evaluation_run,
)
from run_s4_text_baseline import (
    added_line_numbers, find_unreachable_after_return,
    read_surface_files,
)
from run_s4_container_build import load_build_report

UNKNOWN = "build configuration, preprocessing, alternative entries and semantic reachability remain unexamined"


def analysis_input(sample: dict) -> dict:
    """Allowlist transport: metadata containing labels is never passed onward."""
    return {
        "sample_id": sample["sample_id"], "project_id": sample["project_id"],
        "base_commit": sample["base_commit"], "head_commit": sample["head_commit"],
        "artifacts": [{key: item[key] for key in ("role", "url", "sha256", "size_bytes")} for item in sample["artifacts"]
                      if item["role"] in {"base_source", "head_source"}],
        "paths": list(sample["surface"]["paths"]),
    }


class AuditedExecutor:
    def __init__(self, inner):
        self.inner = inner
        self.calls = []

    def describe_capabilities(self):
        return self.inner.describe_capabilities()

    def run(self, request, tools):
        entry = {"role": request.role, "attempt_id": request.attempt_id,
                 "evidence_reads": [], "status": "running"}
        # Bind the exact prompt generated by the first-party adapter, without
        # storing prompt text or route credentials in the exported run.
        prompt = (self.inner._prompt(request) if isinstance(self.inner, ClaudeAgentExecutor)
                  else canonical_json(to_plain(request)))
        entry["prompt_digest"] = bytes_digest(prompt.encode("utf-8"))
        self.calls.append(entry)

        class Tools:
            query = tools.query
            resolve_evidence_ref = tools.resolve_evidence_ref

            def read_evidence(self, evidence_id):
                raw = tools.read_evidence(evidence_id)
                entry["evidence_reads"].append({"evidence_id": evidence_id,
                                                 "artifact_digest": bytes_digest(raw)})
                return raw

        started = time.monotonic()
        try:
            result = self.inner.run(request, Tools())
            entry.update(status="completed", sdk_session_id=result.sdk_session_id)
            return result
        except Exception as exc:
            entry.update(status="failed", error_type=type(exc).__name__)
            raise
        finally:
            entry["duration_seconds"] = round(time.monotonic() - started, 6)


class QueryBudget:
    """Count actual backend executions; runtime idempotent cache hits are free."""

    def __init__(self, backend, limit):
        self.backend = backend
        self.remaining = limit

    def __getattr__(self, name):
        return getattr(self.backend, name)

    def query(self, request):
        if self.remaining <= 0:
            raise InvalidInput("backend execution budget exhausted")
        self.remaining -= 1
        return self.backend.query(request)


# Compatibility names for existing scripts/tests resolve to packaged,
# reusable implementations.
ObservationEvaluator = CppUnreachableEvaluator
ReferenceReader = EvidenceReviewExecutor
RecordedJoernObservation = RecordedJoernProgramQuery


def _cfg_summary(payload: dict) -> dict:
    rows = payload.get("rows")
    if not isinstance(rows, list):
        raise InvalidInput("Joern raw artifact has no result groups")
    groups = {}
    for item in rows:
        if (not isinstance(item, dict) or not isinstance(item.get("kind"), str)
                or not isinstance(item.get("nodes"), list) or item["kind"] in groups):
            raise InvalidInput("Joern raw artifact has invalid result groups")
        groups[item["kind"]] = item["nodes"]
    required = {"candidate_methods", "return_nodes", "following_nodes",
                "return_cfg_ancestors", "following_cfg_ancestors"}
    if set(groups) != required:
        raise InvalidInput("Joern raw artifact misses required result groups")

    def method_ids(nodes):
        return {item.get("_id") for item in nodes
                if isinstance(item, dict) and item.get("_label") == "METHOD"}

    return {
        "method_count": len(groups["candidate_methods"]),
        "return_count": len(groups["return_nodes"]),
        "following_node_count": len(groups["following_nodes"]),
        "return_reaches_method_entry": bool(method_ids(groups["return_cfg_ancestors"])),
        "following_reaches_method_entry": bool(method_ids(groups["following_cfg_ancestors"])),
    }


def load_joern_evidence(report_path: Path, manifest: dict) -> dict[str, dict]:
    """Validate a local probe report and load its digest-bound raw artifacts."""
    report_bytes = report_path.read_bytes()
    try:
        report = json.loads(report_bytes)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise InvalidInput("Joern report must be a UTF-8 JSON object") from exc
    if not isinstance(report, dict):
        raise InvalidInput("Joern report must be a JSON object")
    samples = {item["sample_id"]: item for item in manifest["samples"]}
    sample = samples.get(report.get("sample_id"))
    head_artifact = next((item for item in sample["artifacts"] if item["role"] == "head_source"), None) if sample else None
    cpg = report.get("cpg", {})
    surface_cpg = (cpg.get("source_mode") == "verified manifest surface only"
                   and cpg.get("build_recipe_applied") is False
                   and cpg.get("build_status", "not_run") == "not_run")
    build_cpg = (
        cpg.get("source_mode") == "verified full head source with captured compile database"
        and cpg.get("build_recipe_applied") is True
        and cpg.get("build_status") in {"complete", "build_failure"}
        and isinstance(cpg.get("build_report_sha256"), str)
        and isinstance(cpg.get("compile_database_sha256"), str)
        and isinstance(cpg.get("compile_database_normalized_sha256"), str)
    )
    expected = (
        report.get("dataset_id") == manifest["dataset_id"],
        report.get("manifest_digest") == dataset_manifest_digest(manifest),
        sample is not None,
        sample is not None and report.get("head_commit") == sample["head_commit"],
        head_artifact is not None and report.get("head_artifact_sha256") == head_artifact["sha256"],
        sample is not None and report.get("analysis_input", {}).get("surface_paths") == sample["surface"]["paths"],
        report.get("conclusion") == "partial_semantic_evidence_only",
        surface_cpg or build_cpg,
        report.get("backend", {}).get("id") == "joern",
    )
    if not all(expected):
        raise InvalidInput("Joern report is not bound to the frozen manifest surface")
    cpg_sha256 = cpg.get("sha256")
    backend_version = report.get("backend", {}).get("version")
    if not isinstance(cpg_sha256, str) or len(cpg_sha256) != 64 or not isinstance(backend_version, str):
        raise InvalidInput("Joern report has invalid backend provenance")
    report_observations = report.get("observations")
    if not isinstance(report_observations, list):
        raise InvalidInput("Joern report observations must be a list")
    observations = {}
    for observation in report_observations:
        if not isinstance(observation, dict):
            raise InvalidInput("Joern observation must be an object")
        if observation.get("status") == "not_run":
            continue
        required = ("candidate_id", "path", "return_line", "following_line", "raw_sha256",
                    "omissions", "limitations", "cfg_observation")
        if (any(key not in observation for key in required)
                or observation.get("status") != "partial" or observation.get("coverage") != "partial"
                or observation["path"] not in sample["surface"]["paths"]
                or type(observation["return_line"]) is not int
                or type(observation["following_line"]) is not int
                or observation["following_line"] <= observation["return_line"]
                or not isinstance(observation["omissions"], list) or not observation["omissions"]
                or not isinstance(observation["limitations"], list) or not observation["limitations"]):
            raise InvalidInput("Joern observation has invalid partial coverage metadata")
        raw_path = observation.get("raw_path")
        if not isinstance(raw_path, str) or not Path(raw_path).is_absolute() or not Path(raw_path).is_file():
            raise InvalidInput("Joern observation raw artifact is unavailable")
        raw = Path(raw_path).read_bytes()
        if bytes_digest(raw) != observation["raw_sha256"]:
            raise InvalidInput("Joern observation raw artifact digest differs")
        try:
            payload = json.loads(raw)
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise InvalidInput("Joern observation raw artifact must be JSON") from exc
        cfg = observation["cfg_observation"]
        if (not isinstance(payload, dict)
                or payload.get("operation") != "inspect_unreachable_after_return"
                or payload.get("cpg_sha256") != cpg_sha256
                or payload.get("source_path") != observation["path"]
                or payload.get("return_line") != observation["return_line"]
                or payload.get("following_line") != observation["following_line"]
                or not isinstance(cfg, dict)
                or any(type(cfg.get(key)) is not expected_type for key, expected_type in {
                    "method_count": int, "return_count": int, "following_node_count": int,
                    "return_reaches_method_entry": bool, "following_reaches_method_entry": bool,
                }.items())
                or _cfg_summary(payload) != cfg):
            raise InvalidInput("Joern raw artifact does not match its observation")
        candidate_id = observation["candidate_id"]
        if not isinstance(candidate_id, str) or candidate_id in observations:
            raise InvalidInput("Joern observations need unique candidate IDs")
        observations[candidate_id] = {"observation": observation, "raw": raw}
    if not observations:
        raise InvalidInput("Joern report contains no replayable partial observations")
    return {report["sample_id"]: {
        "backend_version": backend_version,
        "report_digest": bytes_digest(report_bytes),
        "cpg_sha256": cpg_sha256,
        "build_status": cpg.get("build_status", "not_run"),
        "build_report_digest": cpg.get("build_report_sha256"),
        "compile_database_sha256": cpg.get("compile_database_sha256"),
        "compile_database_normalized_sha256": cpg.get("compile_database_normalized_sha256"),
        "observations": observations,
    }}


def analyze_sources(view: dict, base: dict[str, str], head: dict[str, str],
                    root: Path, executor_factory, *, max_candidates: int = 10,
                    semantic_bundle: dict | None = None,
                    build_bundle: dict | None = None) -> dict:
    """The analysis boundary accepts only source inputs, never Oracle labels."""
    started = time.monotonic()
    findings = [item for path, text in head.items()
                for item in find_unreachable_after_return(text, path)
                if item["return_line"] in added_line_numbers(base[path], text)]
    evaluator = ObservationEvaluator()
    rule = RuleSpec("cpp.lexical-unreachable-after-return", "1", "Review a lexical candidate; text alone cannot establish a defect",
                    (CheckDefinition("source_window", "Retrieve the candidate's original source window", ("source_window",)),
                     CheckDefinition("semantic_validation", UNKNOWN, ("semantic_unreachable",))),
                    evaluator.evaluator_id, evaluator.evaluator_version)
    operations = ["read_source"] + (["read_recorded_joern"] if semantic_bundle else [])
    policy = digest({"operations": operations, "max_lines": 200, "max_bytes": 16384})
    profile = Profile("source-review", "1", rule.rule_id, rule.rule_version,
                      (RoleDefinition("investigator", "investigator", allowed_operations=("read_source",)),
                       RoleDefinition("verifier", "verifier", allowed_operations=("read_source",))), policy)
    snapshot = FixedSnapshot(
        view["project_id"], view["sample_id"], FrozenSourceProgramQuery.source_digest(head),
        analysis_profile_digest(rule, profile=profile), policy,
        {"base_commit": view["base_commit"], "head_commit": view["head_commit"],
         "coverage_basis": "frozen PR source surface with optional verified build/semantic inputs",
         "build_report_digest": build_bundle["report_digest"] if build_bundle else None,
         "build_status": build_bundle["report"]["build"]["status"] if build_bundle else "not_run",
         "compile_database_normalized_sha256": (
             build_bundle["report"]["compile_database"]["normalized_sha256"]
             if build_bundle else None)},
    )
    backend = QueryBudget(FrozenSourceProgramQuery(snapshot, head), max_candidates * 13)
    semantic_backend = (QueryBudget(RecordedJoernObservation(snapshot, semantic_bundle), max_candidates)
                        if semantic_bundle else None)
    discovered = {item["candidate_id"]: item for item in findings}
    if semantic_bundle:
        for candidate_id, entry in semantic_bundle["observations"].items():
            finding = discovered.get(candidate_id)
            observation = entry["observation"]
            if (finding is None or any(finding[key] != observation[key]
                                       for key in ("path", "return_line", "following_line"))):
                raise InvalidInput("Joern observation does not match source discovery")
    root.mkdir(parents=True, exist_ok=False)
    store = SQLiteStore(root / "runtime.sqlite3", root / "artifacts")
    agent = AuditedExecutor(executor_factory(snapshot, root))
    observed = []
    try:
        runtime = DefectRuntime(store, evaluator=evaluator)
        analysis_id = runtime.create_analysis(snapshot, rule, profile=profile)
        for index, finding in enumerate(findings):
            identity = CandidateIdentity(rule.rule_id, rule.rule_version, snapshot.snapshot_digest,
                                         {"path": finding["path"], "line": finding["return_line"],
                                          "following_line": finding["following_line"]},
                                         f"{finding['path']}:{finding['return_line']}")
            task = runtime.propose_candidate(analysis_id, identity, discovery_ref=f"lexical:{finding['candidate_id']}")
            item = {**finding, "task_id": task.task_id, "status": "not_run"}
            observed.append(item)
            if index >= max_candidates:
                item["blockers"] = ["candidate execution budget exhausted"]
                continue
            start = max(1, finding["return_line"] - 12)
            end = min(len(head[finding["path"]].splitlines()), finding["following_line"] + 12)
            outcome, ref = runtime.query_program(QueryRequest(
                str(uuid.uuid4()), task.task_id, "source_window", "read_source", snapshot.snapshot_digest,
                backend.backend_id, backend.backend_version, policy,
                {"scope_id": snapshot.scope_id, "selectors": {"path": finding["path"]}, "max_results": 1},
                {"path": finding["path"], "start_line": start, "end_line": end},
                f"source:{task.task_id}", 1000,
            ), backend)
            if ref is None:
                decision = runtime.mark_inconclusive(task.task_id, ("source evidence query failed",))
                item.update(status="execution_failure", blockers=list(decision.blockers))
                continue
            fact = FactAssessment(str(uuid.uuid4()), task.task_id, "source_window", "source_window",
                                  "positive", (ref,), identity.scope, "tool_observed",
                                  limitations=("observation establishes text availability only",))
            runtime.record_fact(fact)
            runtime.update_check(CheckItem("source_window", task.task_id, "source_window", "complete",
                                           "supported", (ref,), outcome.coverage))
            semantic_entry = semantic_bundle["observations"].get(finding["candidate_id"]) if semantic_bundle else None
            if semantic_entry:
                semantic_outcome, semantic_ref = runtime.query_program(QueryRequest(
                    str(uuid.uuid4()), task.task_id, "semantic_validation", "read_recorded_joern",
                    snapshot.snapshot_digest, semantic_backend.backend_id, semantic_backend.backend_version, policy,
                    {"scope_id": snapshot.scope_id,
                     "selectors": {"candidate_id": finding["candidate_id"]}, "max_results": 1},
                    {"candidate_id": finding["candidate_id"],
                     "report_digest": semantic_bundle["report_digest"],
                     "cpg_sha256": semantic_bundle["cpg_sha256"]},
                    f"semantic:{task.task_id}", 1000,
                ), semantic_backend)
                if semantic_ref is None or semantic_outcome.status != "partial":
                    raise InvalidInput("verified Joern replay did not produce partial evidence")
                semantic_fact = FactAssessment(
                    str(uuid.uuid4()), task.task_id, "semantic_validation", "semantic_unreachable",
                    "unknown", (semantic_ref,), identity.scope, "tool_observed",
                    limitations=tuple(semantic_outcome.limitations),
                )
                runtime.record_fact(semantic_fact)
                runtime.update_check(CheckItem(
                    "semantic_validation", task.task_id, UNKNOWN, "partial", "unknown",
                    (semantic_ref,), semantic_outcome.coverage, (UNKNOWN,),
                    tuple(semantic_outcome.limitations),
                ))
                item.update(semantic_evidence_id=semantic_ref.evidence_id,
                            semantic_artifact_digest=semantic_ref.artifact_digest,
                            semantic_report_digest=semantic_bundle["report_digest"])
            before = len(agent.calls)
            decision = RoleCoordinator(runtime, agent, backend, owner_id="s4-worker",
                                       working_dir=str(root), token_budget=12000).run_candidate(task.task_id)
            calls = agent.calls[before:]
            failures = [call for call in calls if call["status"] == "failed"]
            status = ("timeout" if any(call.get("error_type") == "TimeoutError" for call in failures)
                      else "execution_failure" if failures else decision.verdict)
            item.update(status=status, verdict=decision.verdict, blockers=list(decision.blockers),
                        evidence_id=ref.evidence_id, artifact_digest=ref.artifact_digest,
                        role_calls=calls, checks=runtime.checks(task.task_id))
        report = runtime.get_report(analysis_id)
        query_count = len(store.list("query", analysis_id))
    finally:
        store.close()
    reopened = SQLiteStore(root / "runtime.sqlite3", root / "artifacts")
    try:
        restored = DefectRuntime(reopened).get_report(analysis_id)
        if restored != report:
            raise InvalidInput("runtime report changed after reopening storage")
    finally:
        reopened.close()
    (root / "runtime-report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    return {"sample_id": view["sample_id"], "candidates": observed, "role_calls": agent.calls,
            "analysis_id": analysis_id, "reopened_report_verified": True,
            "query_count": query_count, "duration_seconds": round(time.monotonic() - started, 6),
            "build": ({"report_digest": build_bundle["report_digest"],
                       "status": build_bundle["report"]["build"]["status"],
                       "compile_database": build_bundle["report"]["compile_database"],
                       "container": build_bundle["report"]["container"]}
                      if build_bundle else None)}


def score_sample(sample: dict, observation: dict, executor: str, sources: dict) -> dict:
    """Offline scoring happens after both roles and the runtime decision finish."""
    candidates = observation["candidates"]
    defects = []
    for defect in sample["known_defects"]:
        matches = [item for item in candidates if item["path"] == defect["location"]["path"]
                   and item["return_line"] == defect["location"]["line"]]
        for item in matches:
            item["known_defect_id"] = defect["defect_id"]
        defects.append({"defect_id": defect["defect_id"], "evaluable": True,
                        "candidate_status": "matched" if matches else "missed",
                        "candidate_ids": [item["candidate_id"] for item in matches],
                        "evidence_status": "partial" if any(item.get("evidence_id") for item in matches) else "missing",
                        "verdict": ("not_run" if matches and all(item["status"] == "not_run" for item in matches)
                                    else "inconclusive" if matches else "missed"), "excluded": False})
    statuses = {item["status"] for item in candidates}
    build = observation.get("build")
    semantic_replayed = any(item.get("semantic_evidence_id") for item in candidates)
    index_omission = (
        "a compile-database CPG was generated, but the configured target build failed; semantic coverage remains partial"
        if semantic_replayed and build and build["status"] == "build_failure" else
        "frozen-build semantic index was not executed; the recorded surface-only Joern observation remains partial"
        if semantic_replayed else
        "build and semantic index were not executed; translation-unit coverage is unavailable"
    )
    return {"sample_id": sample["sample_id"],
            "analysis_status": ("build_failure" if build and build["status"] == "build_failure"
                                else "timeout" if "timeout" in statuses
                                else "execution_failure" if "execution_failure" in statuses
                                else "complete"),
            "coverage": {"total_targets": 1, "analyzed_targets": 1,
                         "total_translation_units": (build["compile_database"]["translation_units"] if build else 0),
                         "analyzed_translation_units": 0,
                         "lines_scanned": sum(len(text.splitlines()) for text in sources.values()),
                         "lines_changed": sample["surface"]["changed_lines"],
                         "omissions": ["target coverage describes lexical scanning of declared PR surface only",
                                       index_omission,
                                       "lexical candidates cannot establish semantic evidence sufficiency",
                                       "discovery only considers return statements introduced or replaced by the PR",
                                       "the broad known-defect denominator also includes classes unsupported by lexical discovery"]},
            "resource": {"duration_seconds": observation["duration_seconds"], "query_count": observation["query_count"],
                         "model_tokens": None if executor == "claude" and observation["role_calls"] else 0,
                         "cost_usd": None if executor == "claude" and observation["role_calls"] else 0},
            "known_defects": defects, "candidates": candidates, "alerts": [],
            "runtime": {key: value for key, value in observation.items() if key != "candidates"}}


def local_route():
    settings = json.loads((Path.home() / ".claude/settings.json").read_text())
    env = settings.get("env", {})
    url = urlsplit(env.get("ANTHROPIC_BASE_URL", ""))
    if url.scheme != "http" or url.hostname not in {"127.0.0.1", "localhost"}:
        raise InvalidInput("CC Switch local Claude route is not active")
    sdk_env = {key: value for key, value in env.items()
               if key.startswith(("ANTHROPIC_", "CLAUDE_CODE_")) and isinstance(value, str)}
    alias = env.get("ANTHROPIC_DEFAULT_SONNET_MODEL", "claude-sonnet-4-6")
    return sdk_env, alias, f"cc-switch:{url.netloc};alias={alias};actual_upstream=unavailable"


def freeze_code(root: Path) -> dict:
    """Keep the executed first-party source, not just a mutable version label."""
    repository = Path(__file__).resolve().parents[1]
    files = [
        Path(__file__).resolve(),
        Path(__file__).resolve().with_name("run_s4_text_baseline.py"),
        Path(__file__).resolve().with_name("run_s4_container_build.py"),
    ]
    files.extend(repository.joinpath("src/agent_runtime").rglob("*.py"))
    manifest = {}
    for path in sorted(files):
        relative = path.relative_to(repository)
        body = path.read_bytes()
        destination = root / "code-snapshot" / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(body)
        manifest[str(relative)] = bytes_digest(body)
    result = {"code_version": digest(manifest), "files": manifest}
    (root / "code-manifest.json").write_text(json.dumps(result, indent=2) + "\n")
    return result


def assert_code_unchanged(frozen: dict) -> None:
    repository = Path(__file__).resolve().parents[1]
    if any(bytes_digest((repository / path).read_bytes()) != expected
           for path, expected in frozen["files"].items()):
        raise InvalidInput("analysis code changed during the run; rerun from a fixed code snapshot")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--work-dir", type=Path, required=True, help="New directory for durable state and artifacts")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--joern-report", type=Path, action="append", default=[],
                        help="Verified surface-only Joern probe report; may be repeated")
    parser.add_argument("--build-report", type=Path, action="append", default=[],
                        help="Verified offline container-build report; may be repeated")
    parser.add_argument("--executor", choices=("reference", "claude"), default="reference")
    parser.add_argument("--cc-switch", action="store_true")
    parser.add_argument("--role-timeout", type=float, default=90)
    parser.add_argument("--max-candidates", type=int, default=2)
    args = parser.parse_args()
    if args.max_candidates < 1 or not 0 < args.role_timeout < float("inf"):
        parser.error("candidate count and role timeout must be positive and finite")
    if args.executor == "claude" and not args.cc_switch:
        parser.error("this runner requires --cc-switch for explicit local SDK routing")
    manifest = load_json_object(args.manifest)
    frozen_digest = dataset_manifest_digest(manifest)
    semantic_bundles = {}
    for report_path in args.joern_report:
        for sample_id, bundle in load_joern_evidence(report_path, manifest).items():
            if sample_id in semantic_bundles:
                raise InvalidInput(f"duplicate Joern report for sample: {sample_id}")
            semantic_bundles[sample_id] = bundle
    build_bundles = {}
    for report_path in args.build_report:
        for sample_id, bundle in load_build_report(report_path, manifest).items():
            if sample_id in build_bundles:
                raise InvalidInput(f"duplicate build report for sample: {sample_id}")
            build_bundles[sample_id] = bundle
    for sample_id, semantic in semantic_bundles.items():
        if semantic["build_report_digest"]:
            build = build_bundles.get(sample_id)
            if build is None or build["report_digest"] != semantic["build_report_digest"]:
                raise InvalidInput("build-aware Joern report needs its exact verified build report")
            compile_db = build["report"]["compile_database"]
            if (semantic["build_status"] != build["report"]["build"]["status"]
                    or semantic["compile_database_sha256"] != compile_db["sha256"]
                    or semantic["compile_database_normalized_sha256"] != compile_db["normalized_sha256"]):
                raise InvalidInput("Joern report and build report provenance differ")
    route = "not_used:deterministic-reference-reader"
    sdk_env, alias = {}, None
    if args.executor == "claude":
        sdk_env, alias, route = local_route()
    args.work_dir.mkdir(parents=True, exist_ok=False)
    frozen_code = freeze_code(args.work_dir)

    def factory(snapshot, root):
        if args.executor == "reference":
            return ReferenceReader()
        return ClaudeAgentExecutor(ClaudeConfig(str(root), "frozen-source", "1", snapshot.tool_policy_digest,
                                               model=alias, sdk_env=sdk_env, max_turns=6,
                                               max_budget_usd=1, role_timeout_seconds=args.role_timeout))

    results = []
    for index, sample in enumerate(manifest["samples"]):
        view = analysis_input(sample)
        sources = {}
        for artifact in view["artifacts"]:
            body, _ = fetch_verified_artifact(artifact)
            sources[artifact["role"]] = read_surface_files(body, view["paths"])
        observation = analyze_sources(view, sources["base_source"], sources["head_source"],
                                      args.work_dir / f"sample-{index}", factory,
                                      max_candidates=args.max_candidates,
                                      semantic_bundle=semantic_bundles.get(view["sample_id"]),
                                      build_bundle=build_bundles.get(view["sample_id"]))
        results.append(score_sample(sample, observation, args.executor, sources["head_source"]))
        print(json.dumps({"sample_id": sample["sample_id"], "candidates": len(observation["candidates"]),
                          "role_calls": len(observation["role_calls"]), "status": results[-1]["analysis_status"]}), flush=True)
    assert_code_unchanged(frozen_code)
    prompts = {f"{index}:{call['attempt_id']}": call["prompt_digest"]
               for index, result in enumerate(results) for call in result["runtime"]["role_calls"]}
    run = {"schema_version": {"major": 1, "minor": 0}, "run_id": f"runtime:{args.executor}:{uuid.uuid4()}",
           "dataset_id": manifest["dataset_id"], "manifest_digest": frozen_digest, "created_at": utc_now(),
           "bindings": {"code_version": frozen_code["code_version"],
                        "environment": {"python": platform.python_version(), "platform": platform.system(),
                                        "machine": platform.machine(),
                                        "claude_agent_sdk": importlib.metadata.version("claude-agent-sdk") if args.executor == "claude" else "not_used"},
                        "rule": {"id": "cpp.lexical-unreachable-after-return", "version": "1"},
                        "backend": {"id": ("frozen-source+recorded-joern" if semantic_bundles else "frozen-source"),
                                    "version": "1"}, "prompt_digests": prompts,
                        "semantic_inputs": {
                            sample_id: {key: bundle[key] for key in ("backend_version", "report_digest", "cpg_sha256")}
                            for sample_id, bundle in semantic_bundles.items()
                        },
                        "build_inputs": {
                            sample_id: {"report_digest": bundle["report_digest"],
                                        "status": bundle["report"]["build"]["status"],
                                        "image_id": bundle["report"]["container"]["image_id"],
                                        "package_lock_sha256": bundle["report"]["container"]["package_lock_sha256"],
                                        "compile_database_normalized_sha256": bundle["report"]["compile_database"]["normalized_sha256"]}
                            for sample_id, bundle in build_bundles.items()
                        },
                        "model_route": route, "executor": args.executor,
                        "budget": {"wall_time_seconds": args.role_timeout * args.max_candidates * 2 * len(results),
                                   "query_limit": args.max_candidates * (14 if semantic_bundles else 13) * len(results), "token_limit": 0,
                                   "cost_limit_usd": 2 * args.max_candidates * len(results) if args.executor == "claude" else 0},
                        "budget_enforcement": {"role_timeout_seconds": args.role_timeout, "max_candidates_per_sample": args.max_candidates,
                                               "token_limit": "unavailable", "query_limit": "backend_executions", "wall_time": "role_calls_only"},
                        "top_k": 10}, "sample_results": results}
    validate_evaluation_run(run, manifest)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(run, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps({"status": "completed", "output": str(args.output.resolve()), "model_route": route}))


if __name__ == "__main__":
    main()
