"""Evidence-first defect analysis runtime.

The core package has no Claude SDK or static-analysis-tool import dependency.
"""

from .context import ContextViewBuilder
from .codec import bytes_digest, canonical_json, digest
from .coordinator import RoleCoordinator
from .discovery import (
    ClangUseAfterFreeDiscoverer,
    CppUnreachableDiscoverer,
    PortfolioDiscoverer,
    added_line_numbers,
    find_unreachable_after_return,
)
from .domain import (
    AnalysisSnapshot,
    Assessment,
    CandidateIdentity,
    CandidateIdentityDraft,
    CandidateKey,
    CandidateTask,
    CheckDefinition,
    CheckItem,
    Claim,
    ContextView,
    Coverage,
    DiscoveryInput,
    DiscoveredCandidate,
    DiscoveryOrigin,
    EvidencePlan,
    EvidenceRef,
    ExclusionRecord,
    FactAssessment,
    FixedSnapshot,
    GenericProvisionalCandidate,
    Handoff,
    ProvisionalCandidate,
    Profile,
    QueryOutcome,
    QueryRequest,
    QueryScope,
    RuleDecision,
    RuleSpec,
    RoleDefinition,
    SourceLocation,
    SpecialistNote,
    StructuredQueryScope,
)
from .errors import (
    BackendFailure,
    CapabilityUnavailable,
    Conflict,
    ContextBudgetExceeded,
    EvidenceIntegrityError,
    InvalidInput,
    PolicyDenied,
    RuntimeFailure,
    SessionUnavailable,
    StaleSnapshot,
    StorageFailure,
)
from .ports import (
    AgentCapabilities,
    AgentExecutor,
    AdaptiveEvidencePlanner,
    CandidateIdentityPolicy,
    CandidateDiscoverer,
    CheckPlanner,
    EvidencePlanSelection,
    ProgramQuery,
    ProgramResult,
    QueryOperation,
    RoleRunRequest,
    RoleRunResult,
    RuleEvaluator,
)
from .runtime import (
    DefectRuntime, NullReturnEvaluator, analysis_profile_digest,
    decision_input_digest, null_return_rule,
)
from .executors import EvidenceReviewExecutor
from .pipeline import AnalysisPipeline, PipelineCandidateResult, PipelineRunResult
from .lifetime_candidates import (
    ASYNC_MEMBER_DESTRUCTION_RULE,
    CONTAINER_INVALIDATION_RULE,
    COROUTINE_DESTRUCTION_RULE,
    RETURNED_RESOURCE_RULE,
    STACK_CONTEXT_ESCAPE_RULE,
    VECTOR_FIELD_COPY_RULE,
    AsanChecklist,
    AsanEvidenceResult,
    LifetimeCandidate,
    build_asan_checklist,
    normalize_asan_result,
    scan_cpp_paths,
    scan_cpp_source,
)
from .rules import (
    CPP_USE_AFTER_FREE_UNKNOWN,
    CPP_UNREACHABLE_UNKNOWN,
    CppUseAfterFreeEvaluator,
    CppUnreachableEvaluator,
    cpp_use_after_free_profile,
    cpp_use_after_free_rule,
    cpp_unreachable_profile,
    cpp_unreachable_rule,
)
from .session import Lease, SessionBinding, SessionService
from .store import Mutation, SQLiteStore
from .validation import (
    VALIDATION_RECORD_SCHEMA_VERSION,
    ValidationArtifact,
    ValidationBuildOutcome,
    ValidationExecutionOutcome,
    ValidationIsolationOutcome,
    ValidationRecord,
    ValidationResource,
    ValidationTermination,
    load_validation_record,
    validation_evidence_bundle_bytes,
    validation_record_to_dict,
)

__all__ = [
    "AgentCapabilities",
    "AgentExecutor",
    "AdaptiveEvidencePlanner",
    "ASYNC_MEMBER_DESTRUCTION_RULE",
    "AnalysisSnapshot",
    "AsanChecklist",
    "AsanEvidenceResult",
    "Assessment",
    "CandidateIdentity",
    "CandidateIdentityDraft",
    "CandidateIdentityPolicy",
    "CandidateDiscoverer",
    "bytes_digest",
    "BackendFailure",
    "CandidateKey",
    "CandidateTask",
    "CapabilityUnavailable",
    "CheckDefinition",
    "CheckPlanner",
    "CheckItem",
    "Claim",
    "canonical_json",
    "Conflict",
    "CONTAINER_INVALIDATION_RULE",
    "COROUTINE_DESTRUCTION_RULE",
    "RETURNED_RESOURCE_RULE",
    "STACK_CONTEXT_ESCAPE_RULE",
    "VECTOR_FIELD_COPY_RULE",
    "ContextBudgetExceeded",
    "ContextView",
    "ContextViewBuilder",
    "Coverage",
    "ClangUseAfterFreeDiscoverer",
    "CppUnreachableDiscoverer",
    "CppUnreachableEvaluator",
    "CppUseAfterFreeEvaluator",
    "DefectRuntime",
    "DiscoveryInput",
    "DiscoveredCandidate",
    "DiscoveryOrigin",
    "decision_input_digest",
    "digest",
    "EvidenceIntegrityError",
    "EvidencePlan",
    "EvidencePlanSelection",
    "EvidenceReviewExecutor",
    "EvidenceRef",
    "ExclusionRecord",
    "FactAssessment",
    "FixedSnapshot",
    "GenericProvisionalCandidate",
    "Handoff",
    "InvalidInput",
    "Lease",
    "LifetimeCandidate",
    "Mutation",
    "NullReturnEvaluator",
    "PolicyDenied",
    "ProgramQuery",
    "ProgramResult",
    "QueryOperation",
    "ProvisionalCandidate",
    "Profile",
    "AnalysisPipeline",
    "PipelineCandidateResult",
    "PipelineRunResult",
    "PortfolioDiscoverer",
    "QueryOutcome",
    "QueryRequest",
    "QueryScope",
    "RoleCoordinator",
    "RoleRunRequest",
    "RoleRunResult",
    "RuleDecision",
    "RuleEvaluator",
    "RuleSpec",
    "RoleDefinition",
    "RuntimeFailure",
    "SQLiteStore",
    "SessionBinding",
    "SessionService",
    "SessionUnavailable",
    "SourceLocation",
    "SpecialistNote",
    "StructuredQueryScope",
    "VALIDATION_RECORD_SCHEMA_VERSION",
    "ValidationArtifact",
    "ValidationBuildOutcome",
    "ValidationExecutionOutcome",
    "ValidationIsolationOutcome",
    "ValidationRecord",
    "ValidationResource",
    "ValidationTermination",
    "StaleSnapshot",
    "StorageFailure",
    "build_asan_checklist",
    "null_return_rule",
    "analysis_profile_digest",
    "added_line_numbers",
    "find_unreachable_after_return",
    "normalize_asan_result",
    "load_validation_record",
    "validation_evidence_bundle_bytes",
    "validation_record_to_dict",
    "scan_cpp_paths",
    "scan_cpp_source",
    "cpp_unreachable_profile",
    "cpp_unreachable_rule",
    "CPP_UNREACHABLE_UNKNOWN",
    "CPP_USE_AFTER_FREE_UNKNOWN",
    "cpp_use_after_free_profile",
    "cpp_use_after_free_rule",
]
